apiVersion: v1
kind: Service
metadata:
  name: hello-cloudbuild
  namespace: cloudbuild-ns
spec:
  selector:
    app: hello-cloudbuild
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer