apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicd-app
  namespace: argocd
spec:
  project: cicd-project
  source:
    repoURL: https://github.com/hoangduy1912/demo-k8s.git
    targetRevision: main
    path: application-config
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true